In [ ]:
!pip install numpy


In [ ]:
import numpy as np
#creating array
a = np.array([10,20,30,"Kavya"])
print(a)



['10' '20' '30' 'Kavya']


In [ ]:
# dimensions:ndim tells the number of dimensions.
a=np.array(15)
b=np.array([1,2,3,4])
c=np.array([[4,5,6,7],[6,7,9,10]])
print("a dimension:",a.ndim)
print("b dimension:",b.ndim)
print("c dimension:",c.ndim)



a dimension: 0
b dimension: 1
c dimension: 2


In [ ]:
#shape:shape gives rows and columns.
a=np.array([[4,5,6,7],[6,7,9,10]])
print("shape of a is :",a.shape)



shape of a is : (2, 4)


In [ ]:
# Dtype:dtype shows the datatype of elements.
a= np.array([1,2,3])
print(a.dtype)


int64


In [ ]:
# size/length:size gives total number of elements.

a = np.array([[1,2,3],[4,5,6]])
print(a.size)

6


In [ ]:
# arange(): Creates array with range values.
a = np.arange(1,10)
print(a)

[1 2 3 4 5 6 7 8 9]


In [ ]:
# eye():Identity matrix
a = np.eye(6)
print(a)

[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]


In [ ]:
#zeros(): Creates array filled with zeros
a = np.zeros((2,3))
print(a)

[[0. 0. 0.]
 [0. 0. 0.]]


In [23]:
#Ones():Creates array filled with ones.
a = np.ones((2,2))
print(a)

[[1. 1.]
 [1. 1.]]


In [25]:
# full():Creates array with specified value.
a = np.full((2,2),8)
print(a)

[[8 8]
 [8 8]]


In [27]:
#diag():Creates diagonal matrix.
a = np.diag([1,2,3,4,5])
print(a)

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


In [29]:
#reshape():changes shape of array
a = np.arange(6)
print(a.reshape(2,3))

[[0 1 2]
 [3 4 5]]


In [32]:
#Ravel/flatten(): Converts multi-dimension array into 1D.
a = np.array([[[1,2],[3,4],[5,6]]])
print(a.ravel())


[1 2 3 4 5 6]


In [41]:
# Array Indexing(): Accessing elements using index.
#1d:
a = np.array([10,20,30,40,50,60])

print(a[3])
#2d:A 2D array is like a table (rows and columns).
a = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

print(a[0, 0])
print(a[0, 2])
print(a[1, 1])
#3d:
a = np.array([
    [[1, 2, 3], [4, 5, 6]],
    [[7, 8, 9], [10, 11, 12]]
])

print(a[0,0,0])
print(a[0,1,2])
print(a[1,0,1])

40
1
3
5
1
6
8


In [45]:
# Array slicing: Extract part of array.
#1d:
a = np.array([10, 20, 30, 40, 50, 60])
print("Original Array:", a)

print("arr[1:4] =", a[1:4])
print("arr[:3] =", a[:3])
print("arr[2:] =", a[2:])
print("arr[::2] =", a[::2])
#2d:array[row_start:row_end , column_start:column_end]
a = np.array([
    [1,2,3,4],
    [5,6,7,8],
    [9,10,11,12]
])

print("Original Array:\n", a)

print("First two rows:\n", a[0:2, :])

print("First two columns:\n", a[:, 0:2])

print("Middle elements:\n", a[1:3, 1:3])

#3d:array[layer, row, column]
arr = np.array([
    [[1,2,3],[4,5,6]],
    [[7,8,9],[10,11,12]]
])

print("Original 3D Array:\n", arr)

print("First layer:\n", arr[0])

print("Second layer first row:\n", arr[1,0])

print("All layers first column:\n", arr[:,:,0])





Original Array: [10 20 30 40 50 60]
arr[1:4] = [20 30 40]
arr[:3] = [10 20 30]
arr[2:] = [30 40 50 60]
arr[::2] = [10 30 50]
Original Array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
First two rows:
 [[1 2 3 4]
 [5 6 7 8]]
First two columns:
 [[ 1  2]
 [ 5  6]
 [ 9 10]]
Middle elements:
 [[ 6  7]
 [10 11]]
Original 3D Array:
 [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
First layer:
 [[1 2 3]
 [4 5 6]]
Second layer first row:
 [7 8 9]
All layers first column:
 [[ 1  4]
 [ 7 10]]


In [50]:
# copy,assign,view:view and assign are same
a = np.array([1,2,3])

b = a.copy()
c = a.view()
print(b)
print(c)

[1 2 3]
[1 2 3]


In [69]:
#shares memory:
a = np.array([10, 20, 30, 40])
b = a[1:3]

print("Array a:", a)
print("Array b:", b)

# Check memory sharing
print("Do they share memory?", np.shares_memory(a, b))

# Modify b
b[0] = 99

print("After modifying b:")
print("Array a:", a)
print("Array b:", b)

Array a: [10 20 30 40]
Array b: [20 30]
Do they share memory? True
After modifying b:
Array a: [10 99 30 40]
Array b: [99 30]


In [76]:
# applying conditions:
a = np.array([1,5,8,10])

print(a > 5)

#
arr = np.array([5, 10, 15, 20, 25])

result = np.where((arr > 10) & (arr < 25),True,False)

print(result)

[False False  True  True]
[False False  True  True False]


In [82]:
# Transpose: Converts rows into columns
arr = np.array([[1,2],[3,4]])

print(arr.T)

#hstack(),vstack():horizontal and vertical
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])

print(np.hstack((a,b)))
print(np.vstack((a,b)))

[[1 3]
 [2 4]]
[1 2 3 4 5 6 7 8]
[[1 2 3 4]
 [5 6 7 8]]


In [84]:
#insert and delete:
arr = np.array([1,2,3,4])

print(np.insert(arr,2,10)) # here 2 is index and 10 is value
print(np.delete(arr,1))

[ 1  2 10  3  4]
[1 3 4]


In [86]:
#mathematical operations:
arr = np.array([0,30,90])

print(np.sin(arr))
print(np.cos(arr))
print(np.tan(arr))

[ 0.         -0.98803162  0.89399666]
[ 1.          0.15425145 -0.44807362]
[ 0.         -6.4053312  -1.99520041]


In [88]:
# ExponentiaL:
arr = np.array([1,2,3])

print(np.exp(arr))

[ 2.71828183  7.3890561  20.08553692]


In [90]:
# sum of array:
arr = np.array([[1,2,3],[4,5,6]])

print(np.sum(arr))
print(np.sum(arr,axis=0))  #axis0 means column,axis1 means row

21
[5 7 9]


In [92]:
#mean,median,mode,std:
arr = np.array([1,2,3,4,5])

print(np.mean(arr))
print(np.median(arr))
print(np.std(arr))

3.0
3.0
1.4142135623730951


In [98]:
# max,min,sort:
arr = np.array([5,2,9,1])

print(np.max(arr))
print(np.min(arr))
print(np.sort(arr))
print(np.sort(arr)[::-1])  # Sort in descending order

9
1
[1 2 5 9]
[9 5 2 1]


In [100]:
#searching(where):
arr = np.array([10,20,30,40])

print(np.where(arr==30))

(array([2]),)


In [106]:
# covert to list/set:
arr = np.array([1,2,3])

print(dir(list))
print(set(arr))
print(dir(dict))

['__add__', '__class__', '__class_getitem__', '__contains__', '__delattr__', '__delitem__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__getstate__', '__gt__', '__hash__', '__iadd__', '__imul__', '__init__', '__init_subclass__', '__iter__', '__le__', '__len__', '__lt__', '__mul__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__reversed__', '__rmul__', '__setattr__', '__setitem__', '__sizeof__', '__str__', '__subclasshook__', 'append', 'clear', 'copy', 'count', 'extend', 'index', 'insert', 'pop', 'remove', 'reverse', 'sort']
{np.int64(1), np.int64(2), np.int64(3)}
['__class__', '__class_getitem__', '__contains__', '__delattr__', '__delitem__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__getstate__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__ior__', '__iter__', '__le__', '__len__', '__lt__', '__ne__', '__new__', '__or__', '__reduce__', '__reduce_ex__', '

In [110]:
#keywords:
arr = np.array([1,2,3], dtype=float)
print(arr)
print(len(arr))

[1. 2. 3.]
3


In [109]:
#flatten:
arr = np.array([[1,2],[3,4]])   #coverts to 1D
print(arr.flatten())

[1 2 3 4]
