In [213]:
!pip install numpy


In [214]:
import numpy as np

In [149]:
a=np.array([1,2,3,4,5,{1,2,3},"madhu"])

In [215]:
a

array(8)

In [216]:
#dimension
x=a.ndim #shows which dimen the array is

In [217]:
x

0

In [ ]:
#datatype
n=a.dtype

In [218]:
n


dtype('int64')

In [219]:
#array dimesions
a=np.array(8)
b=np.array([1,2,3])
c=np.array([[12,11],[30,20]])
d=np.array([[[1,2,3],[2,4,5],[6,8,9]]])

In [220]:
print(a.ndim)#dimensions
print(b.ndim)
print(c.ndim)
print(d.ndim)



print(a.shape)#rows,colums&layer
print(b.shape)
print(c.shape)
print(d.shape)

0
1
2
3
()
(3,)
(2, 2)
(1, 3, 3)


In [221]:
#dtype
a.dtype

dtype('int64')

In [222]:
#type
print(type(b))

<class 'numpy.ndarray'>


In [223]:
#len
len(b)

3

In [224]:
#range
x=np.array(range(1,10))
x

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [225]:
#arange
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [226]:
np.eye(2,2,dtype=int)

array([[1, 0],
       [0, 1]])

In [227]:
np.eye(4,dtype=int)

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

In [228]:
np.zeros((4,4),dtype=int)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [229]:
np.full((5,5),5)

array([[5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5]])

In [230]:
np.diag([1,2,3,4,5])

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

In [231]:
d.ravel()

array([1, 2, 3, 2, 4, 5, 6, 8, 9])

In [232]:
d.flatten()

array([1, 2, 3, 2, 4, 5, 6, 8, 9])

In [233]:
r=d.reshape(3,3)
print(r)
print(r.ndim)
print(r.shape)

[[1 2 3]
 [2 4 5]
 [6 8 9]]
2
(3, 3)


In [234]:
list=np.array(range(2,11))
print(list)
print(list[4])

[ 2  3  4  5  6  7  8  9 10]
6


In [235]:
#indexing
print(b)
print("the elem is:",b[1])
print("dimension is:",b.ndim)

print(c)
print("the elem is:",c[0,1])
print("dimension is:",c.ndim)

print(d)
print("the elem is:",d[0][1][0])
print("dimension is:",d.ndim)


[1 2 3]
the elem is: 2
dimension is: 1
[[12 11]
 [30 20]]
the elem is: 11
dimension is: 2
[[[1 2 3]
  [2 4 5]
  [6 8 9]]]
the elem is: 2
dimension is: 3


In [236]:
# 1 dem Slicing
my_list=np.array(range(0,16))
print(my_list)
print("dimen is:",my_list.ndim)
my_list[2:10:2]


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
dimen is: 1


array([2, 4, 6, 8])

In [237]:
# 2 dem Slicing
two_dim=np.array([[1,2,3],[2,3,4]])
print(two_dim)
print("dimen is:",two_dim.ndim)
two_dim[0:1]

[[1 2 3]
 [2 3 4]]
dimen is: 2


array([[1, 2, 3]])

In [238]:
#3 dem slicing
three_dim=np.array([[[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]]])
print("original one:\n",three_dim)
print("dimen is:",three_dim.ndim)
print("shape is",three_dim.shape)
print("extracting 5 6 9 10")
print(three_dim[0,1:3,0:2])
print("extracting 6 7 10 11 ")
print(three_dim[0,1:3,1:3])
print("extracting 9 10 11 12")
print(three_dim[0,2:3])





original one:
 [[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]
  [13 14 15 16]]]
dimen is: 3
shape is (1, 4, 4)
extracting 5 6 9 10
[[ 5  6]
 [ 9 10]]
extracting 6 7 10 11 
[[ 6  7]
 [10 11]]
extracting 9 10 11 12
[[ 9 10 11 12]]


In [239]:
#cpoy,assign\view
v=c.view()
print(c)
print("\n",v)

cop=c.copy()
print("\n",c)
print("\n",cop)


[[12 11]
 [30 20]]

 [[12 11]
 [30 20]]

 [[12 11]
 [30 20]]

 [[12 11]
 [30 20]]


In [207]:
#modifying data
num1=[1,2,3,4,5,8888]
num2=[20,30,40,50,60]
print(num1)
print(num2)
num1[2]=5555555555
print(num1)

#memory sharing
print(np.shares_memory(num1,num2))


[1, 2, 3, 4, 5, 8888]
[20, 30, 40, 50, 60]
[1, 2, 5555555555, 4, 5, 8888]
False


In [248]:
#insert and delete
num3=np.array([1,2,3,4,5,6,7,8])
print(np.insert(num3,0,10))
print(np.delete(num3,5))




[10  1  2  3  4  5  6  7  8]
[1 2 3 4 5 7 8]


In [256]:
#tranpose,vstack,hstack
arr=np.array([[1,2,3],[4,5,6]])
print(arr.T)

e = np.array([1,2,3,4])
g = np.array([5,6,7,8])

print(np.hstack((e,g)))
print(np.vstack((e,g)))

[[1 4]
 [2 5]
 [3 6]]
[1 2 3 4 5 6 7 8]
[[1 2 3 4]
 [5 6 7 8]]


In [268]:
#mathmetical oper
print(np.sin(e))
print(np.cos(g))
print(np.tan(arr))
print(np.exp(e))
print(np.sum(arr))
#statistical data
print(np.mean(e))
print(np.median(e))
print(np.std(e))
#min,max,sort
print(np.min(e))
print(np.max(e))
print(np.sort(e))

[ 0.84147098  0.90929743  0.14112001 -0.7568025 ]
[ 0.28366219  0.96017029  0.75390225 -0.14550003]
[[ 1.55740772 -2.18503986 -0.14254654]
 [ 1.15782128 -3.38051501 -0.29100619]]
[ 2.71828183  7.3890561  20.08553692 54.59815003]
21
2.5
2.5
1.118033988749895
1
4
[1 2 3 4]


In [271]:
#where
print(np.where(e==4))

(array([3]),)


In [276]:
 #covert to list/set:
arr = np.array([1,2,3])

print(dir(list))
print(set(arr))
print(dir(dict))

['T', '__abs__', '__add__', '__and__', '__array__', '__array_finalize__', '__array_function__', '__array_interface__', '__array_namespace__', '__array_priority__', '__array_struct__', '__array_ufunc__', '__array_wrap__', '__bool__', '__buffer__', '__class__', '__class_getitem__', '__complex__', '__contains__', '__copy__', '__deepcopy__', '__delattr__', '__delitem__', '__dir__', '__divmod__', '__dlpack__', '__dlpack_device__', '__doc__', '__eq__', '__float__', '__floordiv__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__getstate__', '__gt__', '__hash__', '__iadd__', '__iand__', '__ifloordiv__', '__ilshift__', '__imatmul__', '__imod__', '__imul__', '__index__', '__init__', '__init_subclass__', '__int__', '__invert__', '__ior__', '__ipow__', '__irshift__', '__isub__', '__iter__', '__itruediv__', '__ixor__', '__le__', '__len__', '__lshift__', '__lt__', '__matmul__', '__mod__', '__mul__', '__ne__', '__neg__', '__new__', '__or__', '__pos__', '__pow__', '__radd__', '__rand__'